feat: created pv for core app
JanMate/happy_bank_infra pull request #62
Opened 2022-01-02 13:56 UTC by Oleksandr6676

Created pv, pvc and set mounting to core app pod

2022-01-02 14:03 UTC, Oleksandr6676 commented
Hi Jan, I wasn't sure where to mount data inside the container, memory.py?

2022-01-02 14:31 UTC, Oleksandr6676 commented
It seems like I broke  our tests due to incorrect commit message in the first commit. I should have used amend command instead of pushing one more commit...

2022-01-02 15:58 UTC, JanMate commented
> Hi Jan, I wasn't sure where to mount data inside the container, memory.py?

Nope, python files contains only python code - the logic. For storing data, we are gonna use JSON file and parse it with python. Memory usually means non-persistent data storage. Probably, we should rename memory.py file and the path of the mounted file set to something like '/data/'. For money transfer we needs 'users.json' and 'transactions.json' files. So set them to mounting.

Anyway, great catch! 👍🏽 🚀

2022-01-02 16:26 UTC, JanMate commented
> It seems like I broke our tests due to incorrect commit message in the first commit. I should have used amend command instead of pushing one more commit... I'll try to fix it

Sure, your commits must respects [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) due to the semantic versioning.

I recommend you to squash first two commits to avoid the revert commit and set the commit message to adhere the conventions.

2022-01-02 16:31 UTC, JanMate requested changes
Please, fix the mounting and commit messages.

2022-01-02 16:31 UTC, JanMate commented on kubernetes/core-pod.yml
> +          mountPath: /core/data/memory.py
Please, don't mount a code, config and source data files together. It's prefer to place them into separate folders.

2022-01-02 16:31 UTC, JanMate commented on kubernetes/storage.yml
> +      storage: 1Gi
YAML files should contain new line on the end of the file.

2022-01-03 16:42 UTC, JanMate commented
> > It seems like I broke our tests due to incorrect commit message in the first commit. I should have used amend command instead of pushing one more commit... I'll try to fix it
> 
> Sure, your commits must respects [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) due to the semantic versioning.
> 
> I recommend you to squash first two commits to avoid the revert commit and set the commit message to adhere the conventions.

I have already done it because I needed to test semantic release.

2022-01-03 23:25 UTC, JanMate requested changes
Anyway, will it work with the core application if we implement the store logic? Please, verify and discuss if you see any issus with it.

2022-01-03 23:25 UTC, JanMate commented on kubernetes/core-pod.yml
> +          mountPath: /app-data/users.json
So sorry for scam. I didn't realize the mountPath param means directory path, not the certain file.

```suggestion
        - name: core-volume
          mountPath: /data/
```

2022-01-04 17:32 UTC, JanMate commented
Regarding filesystem group permissions check this out: https://stackoverflow.com/questions/43544370/kubernetes-how-to-set-volumemount-user-group-and-file-permissions.

2022-01-04 18:35 UTC, JanMate requested changes
As we discussed today, it requires to set file system group permission to mounted volume.

2022-01-04 21:31 UTC, Oleksandr6676 commented
@JanMate I updated docker image with uid and gid and pushed updated image to my own repository on dockerhub  for testing purposes. https://hub.docker.com/repository/docker/oleksandr6676/flask_image
I also set  fsGroup in core-pod.yml to gid value but it still doesn't work. I'm facing the same issue with permission denied.
I found some issues on stackoverflow  and github which says that pv with type hostPath does not support security context.
https://stackoverflow.com/questions/66025328/kubernetes-fsgroup-not-changing-file-ownership-on-persistentvolume
https://github.com/kubernetes/minikube/issues/1990

2022-01-04 21:35 UTC, Oleksandr6676 commented
> @JanMate I updated docker image with uid and gid and pushed updated image to my own repository on dockerhub for testing purposes. https://hub.docker.com/repository/docker/oleksandr6676/flask_image I also set fsGroup in core-pod.yml to gid value but it still doesn't work. I'm facing the same issue with permission denied. I found some issues on stackoverflow and github which says that pv with type hostPath does not support security context. https://stackoverflow.com/questions/66025328/kubernetes-fsgroup-not-changing-file-ownership-on-persistentvolume [kubernetes/minikube#1990](https://github.com/kubernetes/minikube/issues/1990)

Shall we use another pv type then?

2022-01-07 22:05 UTC, JanMate commented
> > @JanMate I updated docker image with uid and gid and pushed updated image to my own repository on dockerhub for testing purposes. https://hub.docker.com/repository/docker/oleksandr6676/flask_image I also set fsGroup in core-pod.yml to gid value but it still doesn't work. I'm facing the same issue with permission denied. I found some issues on stackoverflow and github which says that pv with type hostPath does not support security context. https://stackoverflow.com/questions/66025328/kubernetes-fsgroup-not-changing-file-ownership-on-persistentvolume [kubernetes/minikube#1990](https://github.com/kubernetes/minikube/issues/1990)
> 
> Shall we use another pv type then?

We should because this stands in the [k8s docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes):
> hostPath - HostPath volume (for single node testing only; WILL NOT WORK in a multi-node cluster; consider using local volume instead)

So consider 'local' or 'ntfs' then.

2022-01-08 15:16 UTC, Oleksandr6676 commented
Tested with updated PV, Dockerfile and securityContext. Issue with permission seems to be fixed

2022-01-08 16:17 UTC, Oleksandr6676 commented
> Tested with updated PV, Dockerfile and securityContext. Issue with permission seems to be fixed

@JanMate Noticed 1 more interesting thing. It's not connected with PV itself but I'm now getting the same 'permission denied' error inside the 'core' folder. Maybe it's because this folder was copied to the docker image and not created by 'core' user?

2022-01-10 22:48 UTC, Oleksandr6676 commented
> > Tested with updated PV, Dockerfile and securityContext. Issue with permission seems to be fixed
> 
> @JanMate Noticed 1 more interesting thing. It's not connected with PV itself but I'm now getting the same 'permission denied' error inside the 'core' folder. Maybe it's because this folder was copied to the docker image and not created by 'core' user?

I fixed "permission denied" error in this PR/commit:
https://github.com/JanMate/happy_bank_core/pull/30/commits/e9327fdad612e7a06bd598c621a570e498a363ba
Core folder is now accessible.

2022-01-12 09:55 UTC, JanMate approved these changes

2022-01-12 09:56 UTC, merged